apiVersion: v1
kind: Service
metadata:
  name: dev-server
  namespace: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
  app: dev-server
